
###############################
# GLOBAL CONFIGURATION
conf:
    image: busybox
    command: ./boot
    environment:
        ## If you are still developing
        ## (flask wsgi restartable on edit + sqllite dbs + print DEBUG level)
        # APP_MODE: development

        # If you are testing something that does not work
        # (containers that do not start anything)
        APP_MODE: debug

        # ## If you need to get serious
        # ## (gunicorn/nginx servers + postgres dbs + print INFO level)
        # APP_MODE: production
###############################


###############################
backend:
  extends:
    service: conf
  image: pdonorio/backend:baroque-1.1
  # image: pdonorio/py3apil
  hostname: restapi
  volumes:
    # Sql lite database
    - restangulask_apilitedb:/dbs
    # Base code
    - ../backend:/code
    # Rest API endpoints
    - ../vanilla/apis:/code/restapi/resources/custom
    # Rest API configuration
    - ../vanilla/specs:/code/confs/endpoints
    # Other libs
    - ../vanilla/libs:/code/libs

###############################

htmlfiles:
  image: alpine
  command: echo 'launched'
  volumes:
    # All the angular personal code (&& templates)
    - ../vanilla/jscode:/data/frontend/felask/static/app
    # js/css libraries installed via bower
    - ../vanilla/libs/bower_components:/data/frontend/felask/static/bower
    # custom fonts files
    - ../vanilla/fonts:/data/frontend/felask/static/fonts
    # custom css files
    - ../vanilla/templates/customcss:/data/frontend/felask/static/css
    # Custom images
    - ../vanilla/img:/data/frontend/felask/static/img/custom
    # Angular blueprint ? What is that?
    - ../vanilla/specs:/data/frontend/config/angular/blueprints

frontend:
  extends:
    service: conf
  image: pdonorio/oldflask
  # image: rapydo/frontend
  hostname: frontend
  working_dir: /data/frontend
  volumes:
    # Sql lite database & common models
    - restangulask_apilitedb:/dbs
    # Main dir. It has to be the root directory, to make links work
    - ..:/data
    # Python pages
    - ../vanilla/pages:/data/frontend/felask/pypages
    # Python templates
    - ../vanilla/templates/python:/data/frontend/felask/templates/custom

###############################
# Make automatic to install libraries
bower:
    image: pdonorio/jsdev
    working_dir: /tmp/vanilla/libs
    volumes:
        - ..:/tmp

#################################
# Database administration

# This image let you access the postgres db with a 'phpmyadmin' like web page
sqladmin:
  image: eudatb2stage/sqladminer:latest
  # Sql lite database & common models
  volumes:
      - restangulask_apilitedb:/dbs
  # links:
  #     - sql:db
  ports:
      - 8888:8888

# proxy:
#   image: nginx:1.11.5-alpine
#   hostname: iamaproxy
#   # command: echo "Hello"

# Nginx proxy
proxy:
  build: ../builds/sslproxy
  #image: nginx:rapydo
  # OLD: using the official image directly with no letsencrypt
  # image: nginx:1.11-alpine
  #command: sleep 1234567890
  hostname: iamaproxy
  environment:
    DOMAIN: spectaclebaroque.eu
    MODE: ""
    # MODE: "--staging"
  volumes:
    - restangulask_sslcerts:/etc/letsencrypt

