
# searchindex:
#   ports:
#     - 9200:9200

# rethinkdb:
#   # Web admin
#   ports:
#     - 7778:8080

#################################
# PRODUCTION performance

proxy:
  links:
    - custombe:api
    - customfe:html
  volumes:
    - ../containers/nginx_proxy:/etc/nginx/conf.d
    - ../frontend/felask/static:/static
    - ../uploads:/data/frontend/felask/static/uploads
  volumes_from:
    - htmlfiles
    # - uploadsdata
  ports:
    - 80:80

custombe:
  command: init
  environment:
    APP_MODE: production
    UWSGI_MASTER: /tmp/uwsgi/starter.ini
    NGINX_ACTIVE: "True"
  volumes:
    - ../containers/wsgi:/tmp/uwsgi
    - ../containers/nginx_internal:/etc/nginx/conf.d
  # ports:
  #   - 80:8080

customfe:
  environment:
    APP_MODE: production
#   command: sleep infinity
# #   volumes_from:
# #     - uploadsdata
